on:
  workflow_dispatch:
    inputs:
      renderID:
        description: "Which message ids should it be?"
        required: true
        default: "clg2m4t7b00b7bu9b0einnxnm"
      backend:
        description: "backend url"
        required: true
        default: https://us-central1-dumbo-3d6e7.cloudfunctions.net/app
name: Render video
jobs:
  render:
    name: Render video
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm i
      - run: npm run build -- --props="$WORKFLOW_INPUT"
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - run: npx ts-node src/upload-and-notify.ts
        env:
          BACKEND: https://us-central1-dumbo-3d6e7.cloudfunctions.net/app
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      - uses: actions/upload-artifact@v2
        with:
          name: out.mp4
          path: out.mp4
