on:
  workflow_dispatch:
    inputs:
      renderId:
        description: "Which message ids should it be?"
        required: true
        default: "clg2m4t7b00b7bu9b0einnxnm"
name: Render video
jobs:
  render:
    name: Render video
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm i
      - run: BACKEND=https://us-central1-dumbo-3d6e7.cloudfunctions.net/app npm run build
        env:
          BACKEND: https://us-central1-dumbo-3d6e7.cloudfunctions.net/app
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      - run: renderID=${{inputs.renderId}} npx ts-node src/upload-and-notify.ts
      - uses: actions/upload-artifact@v2
        with:
          name: out.mp4
          path: out.mp4
